### ISSUE TITLE
Add colors to the output that can be used with `less` command

### ISSUE THREAD

**Issue by oarribas** [givaldolins/openshift-cluster-health-check#17]
Add colors to the output, like "red" for `Errors`, "orange" for `Warning` and "green" for `Info` messages, to be able to use it with `less -r`, similar to which is explained in [1].

[1] https://unix.stackexchange.com/questions/19317/can-less-retain-colored-output

**Comment by givaldolins** [comment]
Hi @oarribas ,
I am using this [library](https://github.com/fatih/color) for colouring the output and couldn't find a way to enable this easily without recoding all output that is coloured. However, I found that what you asked can be easily achieved by adding the **unbuffer** command in front of the `oc hc cluster` command.
This worked for me `$ unbuffer oc hc cluster | less -R`

**Comment by oarribas** [comment]
Thanks @givaldolins , probably not possible to use that with the managed script, as the output of above command is sent to the job's log.
