### ISSUE TITLE
Show info about the cluster

### ISSUE THREAD

**Issue by oarribas** [givaldolins/openshift-cluster-health-check#21]
Show info about the cluster in the report, like `clusterID`, `version`

**Comment by givaldolins** [comment]
After PR https://github.com/givaldolins/openshift-cluster-health-check/pull/24, this is how the clusterversion output will look like: 

1- Cluster running supported version
```
Checking if cluster is EOL...
  [Info] Cluster xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx is running version 4.13.13, which is not more than 2 versions behind from latest minor release (4.13).
```
2- Cluster that reached EOL
```
 [Warning] Cluster eeebc2d5-f0b0-432e-a7ba-39997ee2d6fc is running version 4.10.24, which is more than 2 versions behind the latest minor release available (4.13) and might be out of support or close to reach its EOL.
  Please double check the OpenShift Lifecycle page to confirm that.
```

**Comment by givaldolins** [comment]
@oarribas , please check if the change above is according to what you suggested.

**Comment by oarribas** [comment]
@givaldolins , yes, I think the information is OK now :)

On the other hand, as you are adding the following sentence: `Please double check the OpenShift Lifecycle page to confirm that`, I think a link to that page will be helpful.
